// Tie-lo with tone numbers instead of diacritics
// Input has to be pre-processed before passing to parser

// Codas
%extend codanasal : COD_N
%extend codastops : COD_T

// Tones
tone : TONENUMBER ( "(" TONENUMBER ")" )?
TONENUMBER : "0".."8"

// Syllable separator
// hyphen or apostrophe are also valid punctuation
// usage as syllable separator has priority over use as punctuation
SYLLABLE_SEP.1 : "-" | "'" | "’"

